services:
  dev:
    image: dgit:latest
    build:
      context: ${DOTFILES_CONFIG_DIR}
      dockerfile: .config/docker/dgit/Dockerfile
    volumes:
      - .:/workspace
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-""}
    working_dir: /workspace
    tty: true
    stdin_open: true
