[terminal]
osc52 = "CopyPaste" # docker container から copy するため

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux new -A -s ala"]

[font]
normal = { family = "HackGen Console NF", style = "Regular" }
size = 22

